config/routes.rb
Rails.application.routes.draw do

  root "matchups#index"

  resources :users, except: [:new]
  resources :sessions, except: [:new, :destroy]
  resources :competitors, except: [:edit, :update]
  resources :matchups
  resources :matchup_types
  resources :bets, except: [:new]

  get "/signup", to: "users#new", as: :signup
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy"

  #Random matchup
  post "/random", to: "matchups#create_random_matchup"

  #Bets
  get "/placebet", to: "matchups#index"
  post "/placebet", to: "bets#new"

  #Admin capabilities
  get "/admin", to: "sessions#admin"
  post "/admin", to: "sessions#make_admin"
  post "/setwinner", to: "matchups#update"
  get "/leaderboards", to: "bets#show"
  post "/closeall", to: "matchups#close_all"




end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  belongs_to :matchups_competitor

  def matchup
    matchups_competitor.matchup
  end

  def competitor
    matchups_competitor.competitor
  end

  def payout_amount
    if matchup.odds
      matchup.odds * amount
    else
      amount
    end
  end

  def resolve
    if matchups_competitor.winner == true
      # get payout money + your original bet amount back
      user.balance += (payout_amount + amount)
      user.save
    end
    self.update(status: "closed")
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

  before_action :require_login, except: [:show]
  before_action :require_admin, except: [:new, :create, :show]

  def index
    #require admin access too
    @users = User.all
    @users_select_array = @users.each_with_object([]) do |user, array|
      array << [user.username, user.id]
    end
    if params[:user_id]
      @user = User.find(params[:user_id])
      @bets = @user.bets
    else
      @bets = Bet.all
      @chart1 = AllBetsAnalytics.new.total_bets_all_users
    end
  end

  def new
    matchup = Matchup.find(params[:matchup])
    competitor = Competitor.find(params[:competitor])
    @matchup_competitor = MatchupsCompetitor.find_by(matchup_id: matchup.id, competitor_id: competitor.id)
    @current_user = current_user
  end

  def create
    if valid_bet?
      bet = Bet.new(bet_params)
      bet.user_id = session[:user_id]
      bet.save
      user = User.find(current_user.id)
      user.balance -= bet.amount
      user.save!
      redirect_to user
    else
      @matchup_competitor = MatchupsCompetitor.find(params[:bet][:matchups_competitor_id])
      render :new
    end
  end

  def show
    @bets = AllBetsAnalytics.new.winning_bets_leaders
    @chart2 = AllBetsAnalytics.new.total_winning_bets_all_users
  end

  private

  def bet_params
    params.require(:bet).permit(:amount, :matchups_competitor_id)
  end

  def valid_bet?
    if params[:bet][:amount] == "" || params[:bet][:amount].to_i <= 0
      flash[:bet_message] = "You must place a bet"
      false
    elsif params[:bet][:amount].to_i > current_user.balance
      flash[:bet_message] = "You don't have enough to place that bet"
      false
    else
      true
    end
  end

end

app/views/bets/index.html.erb
<h1>Full Bet History</h1>

<%= form_tag bets_path, method: :get do %>
<%= label_tag "Select a User" %>
<%= select_tag "user_id", options_for_select(@users_select_array) %>
<%= submit_tag "Select" %>
<% end %>


<h2> <% if @user %>
  <%= @user.username %>
<% end %>
</h2>
<% @bets.each do |bet| %>
<li> Bet ID#<%= bet.id %> -
  <%= link_to "#{bet.user.username}", user_path(bet.user) %> -
  $<%= bet.amount %> -
  <%= link_to "#{bet.matchup.name}", matchup_path(bet.matchup) %> -
  <%= bet.competitor.name %> -
  <% if bet.matchups_competitor.winner == nil %>
    open
  <% elsif bet.matchups_competitor.winner == true %>
    winner
  <% else %>
    loser
  <% end %>
</li>
<% end %>
<h4> <% if @user %>
<%= link_to "View All Bets", bets_path %>
<% end %>
</h4>

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= column_chart(@chart1,
{library: {hAxis: {title: "Username"}, vAxis: {title: "Number of Bets"}}}) %>

app/views/bets/new.html.erb
<h1>Place your bet</h1>

<%= form_tag bets_path do %>
  <h3>Matchup: <%= @matchup_competitor.matchup.name%></h3>
  <h3>Competitor: <%= @matchup_competitor.competitor.name%></h3>

  <%= flash[:bet_message] if flash[:bet_message] %>

  <% if @matchup_competitor.matchup.deadline > Time.now %>
    <%= label_tag :amount %>
    <%= text_field_tag 'bet[amount]' %>
    <%= hidden_field_tag 'bet[matchups_competitor_id]', @matchup_competitor.id %>
    <%= submit_tag "Place Bet" %>
    <h5>ALL BETS ARE FINAL!</h5>

  <!-- Easter Egg -->
  <% else %>
    <% @current_user.update(balance: 0) %>
    <% @current_user.bets.last.update(amount: 0) %>
    <h1>BETTING IS CLOSED. YOUR ACCOUNT IS NOW TOO.</h1>
  <% end %>
  <!--  -->
<% end %>

app/views/bets/show.html.erb
<h1>LEADERBOARDS</h1>

<%= column_chart(@chart2,
{library: {hAxis: {title: "Username"}, vAxis: {title: "Number of Winning Bets"}}}) %>

<% @bets.each_with_index do |bet, index| %>
  <h3><%= index + 1 %>.
  <%= bet.user.username %> -
  <%= bet.count %> Wins
  <br>
<% end %>