config/routes.rb
Rails.application.routes.draw do

  root "matchups#index"

  resources :users, except: [:new]
  resources :sessions, except: [:new, :destroy]
  resources :competitors, except: [:edit, :update]
  resources :matchups
  resources :matchup_types
  resources :bets, except: [:new]

  get "/signup", to: "users#new", as: :signup
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy"

  #Random matchup
  post "/random", to: "matchups#create_random_matchup"

  #Bets
  get "/placebet", to: "matchups#index"
  post "/placebet", to: "bets#new"

  #Admin capabilities
  get "/admin", to: "sessions#admin"
  post "/admin", to: "sessions#make_admin"
  post "/setwinner", to: "matchups#update"
  get "/leaderboards", to: "bets#show"
  post "/closeall", to: "matchups#close_all"




end

app/models/matchup.rb
class Matchup < ActiveRecord::Base
  has_many :matchups_competitors
  has_many :competitors, through: :matchups_competitors
  belongs_to :matchup_type

  def winner_mc
    MatchupsCompetitor.find_by(matchup_id: self.id, winner: true)
  end

  def closeable?
    self.deadline < Time.now && self.status == "open"
  end

  def opposing_competitor_to(competitor)
    self.competitors.map(&:name).select{|c| c != competitor.name}.first
  end

  def random_winner
    competitors = self.competitors
    range = rand(1..100)
    if self.closeable?
      if range > 0 && range < 50
        winner = competitors[0]
        loser = competitors[1]
      else
        winner = competitors[1]
        loser = competitors[0]
      end
      won = MatchupsCompetitor.find_by(competitor_id: winner.id, matchup_id: self.id)
      lost = MatchupsCompetitor.find_by(competitor_id: loser.id, matchup_id: self.id)
      # sets the matchups_competitor's winner column to true or false based on result
      won.winner = true
      lost.winner = false
      won.save
      lost.save
      won.bets.each do |bet|
        bet.resolve
      end
      lost.bets.each do |bet|
        bet.resolve
      end
      self.update(status: "closed")
    end
  end

  def set_winner(winner)
    competitors = self.competitors
    if self.closeable?
      # sets the opposite competitor winner column to false and sets the winner (the argument passed in) to true
      loser = competitors.reject {|comp| comp == winner}.first
      won = MatchupsCompetitor.find_by(competitor_id: winner.id, matchup_id: self.id)
      lost = MatchupsCompetitor.find_by(competitor_id: loser.id, matchup_id: self.id)
      won.winner = true
      lost.winner = false
      won.save
      lost.save
      won.bets.each do |bet|
        bet.resolve
      end
      lost.bets.each do |bet|
        bet.resolve
      end
      self.update(status: "closed")
    end
  end

  def get_num_matchups_for_chart
    data = Matchup.group(:matchup_type_id).count
    data.each_with_object({}) { |(key, value), hash| hash[MatchupType.find(key).name] = value }
  end

  def format_time
    self.deadline.strftime("%B %d %Y %I:%M:%S GMT+0200")
  end

  def data_for_bets_pie
    self.get_sum_bets_by_competitor.each_with_object({}) do |obj, hash|
      hash[Competitor.find(obj.competitor).name] = obj.total
    end
  end

  def get_sum_bets_by_competitor
    Matchup.find_by_sql(
    <<-SQL
    SELECT SUM(amount) AS total, competitor_id AS competitor
    FROM matchups_competitors
    JOIN bets ON matchups_competitors.id = bets.matchups_competitor_id
    JOIN matchups
    ON matchups.id = matchups_competitors.matchup_id
    WHERE matchups.id = #{self.id} GROUP BY competitor_id;
    SQL
    )
  end

  def get_total_bets_by_competitor
    Matchup.find_by_sql(
    <<-SQL
    SELECT COUNT(amount) AS total, competitor_id AS competitor
    FROM matchups_competitors
    JOIN bets ON matchups_competitors.id = bets.matchups_competitor_id
    JOIN matchups
    ON matchups.id = matchups_competitors.matchup_id
    WHERE matchups.id = #{self.id} GROUP BY competitor_id;
    SQL
    ).each_with_object({}) do |obj, hash|
      hash[Competitor.find(obj.competitor).name] = obj.total
    end
  end

  private

end

app/models/matchup_type.rb
class MatchupType < ActiveRecord::Base
  has_many :matchups
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController

  before_action :require_login, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @matchups = Matchup.all
    @matchups_open = Matchup.where("deadline > ?", Time.now).order(:deadline)
    @matchups_closed = Matchup.where("deadline < ?", Time.now).order(deadline: :desc)
  end

  def new
    @competitors = Competitor.all.order(:name)
    @types = MatchupType.all
    @matchup = Matchup.new
  end

  def create
    @competitor1 = Competitor.find(competitor1)
    @competitor2 = Competitor.find(competitor2)
    competitors = [@competitor1, @competitor2]
    @matchup_type = MatchupType.find(matchup_type)
    if matchup_name == ""
      if @competitor1.id > @competitor2.id
        name = "#{@competitor2.name} VS #{@competitor1.name}"
      else
        name = "#{@competitor1.name} VS #{@competitor2.name}"
      end
    else
      name = matchup_name.upcase
    end

    if same_competitors?
      redirect_to new_matchup_path
    else
      @matchup = Matchup.new(name: name, deadline: deadline, matchup_type_id: @matchup_type.id)
      @matchup.competitors = competitors.sort_by {|comp| comp.id}
      @matchup.save
      redirect_to @matchup
    end
  end

  def show
    @matchup = Matchup.find(params[:id])
  end

  def edit
    @matchup = Matchup.find(params[:id])
  end

  def update
    matchup = Matchup.find(params[:matchup])
    if params[:random]
      matchup.random_winner
      redirect_to matchup
    else
    winner = Competitor.find(params[:competitor])
    matchup.set_winner(winner)
      redirect_to matchup
    end
  end

  def destroy
    @matchup = Matchup.find(params[:id])
    @matchup.destroy
    redirect_to matchups_path
  end

  def create_random_matchup
    @random_matchup = RandomMatchupGenerator.new.randomize
    @random_matchup.save
    redirect_to @random_matchup
  end

  def close_all
    Matchup.all.each do |matchup|
      if matchup.closeable?
        matchup.random_winner
      end
    end
    redirect_to matchups_path
  end

  private

  def matchup_name
    params[:matchup][:name]
  end

  def competitor1
    params[:competitor1]
  end

  def competitor2
    params[:competitor2]
  end

  def matchup_type
    params[:matchup_type]
  end

  def deadline
    params[:matchup][:deadline]
  end

  def same_competitors?
    if competitor1 == competitor2
      flash[:failed_creation] = "You cannot pick the same competitor for a matchup."
    end
  end

end

app/views/matchups/edit.html.erb
<div class="matchup_edit_header">
  <h1>Who won? Pick the Winner</h2>
</div>

<div class="matchup_name_and_type">
  <h2> <%= @matchup.name %> </h1>
  <h3> <%= @matchup.matchup_type.name %> </h3>
</div>

<div class="competitor_buttons row-fluid">

  <div class="span5">
    <%= form_tag "/setwinner" do %>
    <%= hidden_field_tag 'matchup', @matchup.id  %>
    <%= hidden_field_tag 'competitor', @matchup.competitors.first.id  %>
    <%= submit_tag "#{@matchup.competitors.first.name}" %>
  <% end %>
  </div>

  <div class="span2">
    <h1>vs.</h1>
  </div>

  <div class="span5">
      <%= form_tag "/setwinner" do %>
      <%= hidden_field_tag 'matchup', @matchup.id  %>
      <%= hidden_field_tag 'competitor', @matchup.competitors.last.id  %>
      <%= submit_tag "#{@matchup.competitors.last.name}" %>
    <% end %>

  </div>

</div>


<div class="random_buttons">
  <%= form_tag "/setwinner" do %>
  <%= hidden_field_tag 'random' %>
  <%= hidden_field_tag 'matchup', @matchup.id  %>
  <%= submit_tag "Random Winner" %>
  <% end %>
</div>

app/views/matchups/index.html.erb
 <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% if admin? %>
  <h3 id="create_matchup"><%= link_to "Create a Matchup", new_matchup_path %></h3>
  <h3 id="create_matchup"><%= link_to "Set Random Winners", closeall_path, method: :post %></h3>
<% end %>

<div class="matchups_container">

    <div class="row row-centered">

      <h2 class="open_closed">OPEN</h2>

      <% @matchups_open.each do |matchup| %>

        <a href="/matchups/<%= matchup.id %>">
          <div class="col-xs-6 col-centered col-fixed matchup_blocks">
            <h3> <%= matchup.name %></h3>
          <h4>Competitors</h4>
            <%= matchup.competitors.map(&:name).join(" vs. ") %><br>
          <h4>Type</h4>
          <%= matchup.matchup_type.name %><br>
          <h4>Matchup Date</h4>
          <%= matchup.deadline.strftime("%B %d %Y %H:%M:%S") %><br>
        </div>
      </a>

      <% end %>

    </div>

    <div class="row row-centered">

      <h2 class="open_closed">CLOSED</h2>

      <% @matchups_closed.each do |matchup| %>

        <a href="/matchups/<%= matchup.id %>">
          <div class="col-xs-6 col-centered col-fixed matchup_blocks">
            <h3> <%= matchup.name %></h3>
          <h4>Competitors</h4>
            <%= matchup.competitors.map(&:name).join(" vs. ") %><br>
          <h4>Type</h4>
          <%= matchup.matchup_type.name %><br>
          <h4>Matchup Date</h4>
          <%= matchup.deadline.strftime("%B %d %Y %H:%M:%S") %><br>
          <h4>Winner</h4><% if matchup.winner_mc %>
          <p style="color: red;"><%= matchup.winner_mc.competitor.name %></p>
          <% end %>
        </div>
      </a>

      <% end %>

    </div>

</div>

<div>
  <%= column_chart( @matchups.first.get_num_matchups_for_chart ,
  {library: {hAxis: {title: "Type of Matches"}, vAxis: {title: "Number of Matches"}}}) %>
</div>

app/views/matchups/new.html.erb
<%= form_for @matchup do |f| %>
  <% if flash.any? %>
    <% flash.keys.each do |message| %>
      <%= flash[message] %>
    <% end %>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

<label>Competitor 1</label>
<select name="competitor1">
  <% @competitors.each do |competitor| %>
  <option value= <%= competitor.id %> > <%= competitor.name %></option>
  <% end %>
</select><br>

<label>Competitor 2</label>
<select name="competitor2">
  <% @competitors.each do |competitor| %>
  <option value= <%= competitor.id %> > <%= competitor.name %></option>
  <% end %>
</select><br>

<label>Matchup Type</label>
<select name="matchup_type">
  <% @types.each do |type| %>
  <option value= <%= type.id %> > <%= type.name %></option>
  <% end %>
</select><br>

<%= f.datetime_local_field :deadline, min: Time.zone.today, max: Time.zone.today.next_month %><br>

<%= f.submit "Create A Matchup" %>

<% end %>

<br>&nbsp;
<%= form_tag "/random" do |f| %>
<%= submit_tag "Create A Random Matchup" %>
<% end %>

app/views/matchups/show.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<% if @matchup.deadline > Time.now %>
  <div class="countdown">
    <h4>Time left to place your bets</h4>
    <div id="clockdiv"></div>
  </div>
<% else %>
<div class="matchup_results">
  <h1>CLOSED</h1>
  <% if MatchupsCompetitor.find_by(matchup_id: @matchup.id, winner: true) %>
  <h2>Winner: <%= @matchup.winner_mc.competitor.name %></h2>
  <% else %>
    <%= link_to "Set Winner", edit_matchup_path(@matchup) if admin? %>
  <% end %>
  <% end %>
</div>
<br>

<div class="matchup_name_and_type">
  <h1> <%= @matchup.name %> </h1>
  <h3> <%= @matchup.matchup_type.name %> </h3>
</div>

<div class="competitor_buttons row-fluid">

  <div class="span5">
    <%= form_tag "/placebet" do %>
    <%= hidden_field_tag 'matchup', @matchup.id  %>
    <%= hidden_field_tag 'competitor', @matchup.competitors.first.id  %>
    <% if @matchup.deadline > Time.now %>
      <%= submit_tag "#{@matchup.competitors.first.name}" %>
    <% else %>
      <%= submit_tag "#{@matchup.competitors.first.name}", disabled: true %>
    <% end %>
  <% end %>
  </div>

  <div class="span2">
    <h1>vs.</h1>
  </div>

  <div class="span5">
      <%= form_tag "/placebet" do %>
      <%= hidden_field_tag 'matchup', @matchup.id  %>
      <%= hidden_field_tag 'competitor', @matchup.competitors.last.id  %>
      <% if @matchup.deadline > Time.now %>
        <%= submit_tag "#{@matchup.competitors.last.name}" %>
      <% else %>
        <%= submit_tag "#{@matchup.competitors.last.name}", disabled: true %>
      <% end %>
    <% end %>

  </div>

</div>


  <div class="deadline">
    <h3> <%= @matchup.deadline.strftime("%A, %B %d, '%y") %></h3>
    <h3><%= @matchup.deadline.strftime("%I:%M %p") %></h3>
  </div>

<div class="pie_charts">
  <h3>Total Amount Bet per Competitor</h3>
  <%= pie_chart(@matchup.data_for_bets_pie) %><br>
  <h3>Total Number of Bets per Competitor</h3>
  <%= pie_chart(@matchup.get_total_bets_by_competitor) %>
</div>


<script type="text/javascript">

var deadline = "<%= @matchup.deadline.strftime("%B %d %Y %H:%M:%S UTC-0400") %>";

function getTimeRemaining(endtime){
  var t = Date.parse(endtime) - Date.parse(new Date());
  var seconds = Math.floor( (t/1000) % 60 );
  var minutes = Math.floor( (t/1000/60) % 60 );
  var hours = Math.floor( (t/(1000*60*60)) % 24 );
  var days = Math.floor( t/(1000*60*60*24) );
  return {
    'total': t,
    'days': days,
    'hours': hours,
    'minutes': minutes,
    'seconds': seconds
  };
}

getTimeRemaining(deadline).minutes

function initializeClock(id, endtime){
  var clock = document.getElementById(id);
  var timeinterval = setInterval(function(){
    var t = getTimeRemaining(endtime);
    clock.innerHTML =  t.days + " Days <br>&nbsp;<br>" +
                       t.hours + " Hours <br>&nbsp;<br> " +
                       t.minutes + " Minutes <br>&nbsp;<br> " +
                       t.seconds + " Seconds";
    if(t.total<=0){
      clearInterval(timeinterval);
    }
  },1000);
}

initializeClock('clockdiv', deadline);

</script>