config/routes.rb
Rails.application.routes.draw do

  root "matchups#index"

  resources :users, except: [:new]
  resources :sessions, except: [:new, :destroy]
  resources :competitors, except: [:edit, :update]
  resources :matchups
  resources :matchup_types
  resources :bets, except: [:new]

  get "/signup", to: "users#new", as: :signup
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy"

  #Random matchup
  post "/random", to: "matchups#create_random_matchup"

  #Bets
  get "/placebet", to: "matchups#index"
  post "/placebet", to: "bets#new"

  #Admin capabilities
  get "/admin", to: "sessions#admin"
  post "/admin", to: "sessions#make_admin"
  post "/setwinner", to: "matchups#update"
  get "/leaderboards", to: "bets#show"
  post "/closeall", to: "matchups#close_all"




end

app/controllers/matchup_types_controller.rb
class MatchupTypesController < ApplicationController

  def index
    @matchup_types = MatchupType.all
  end

  def new
    @matchup_type = MatchupType.new
  end

  def create
    @matchup_type = MatchupType.create(name: params[:matchup_type][:name])
    redirect_to @matchup_type
  end

  def show
    @matchup_type = MatchupType.find(params[:id])
  end

  def destroy
    @matchup_type = MatchupType.find(params[:id])
    @matchup_type.destroy
    redirect_to matchup_types_path
  end

end

app/views/matchup_types/index.html.erb
<h1>All Matchup Types</h1>

<ul>
<% @matchup_types.each do |mt| %>
  <li><%= link_to mt.name, mt %></li>
<% end %>
</ul>

<%= link_to 'Add New Matchup Type', new_matchup_type_path %>

app/views/matchup_types/new.html.erb
<h1>Add Matchup Type</h1>

<%= form_for @matchup_type do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.submit "Add" %>
<% end %>

app/views/matchup_types/show.html.erb
<h1><%= @matchup_type.name %></h1><br>
<%= link_to 'View All Matchup Types', matchup_types_path %>