config/routes.rb
Rails.application.routes.draw do

  root "matchups#index"

  resources :users, except: [:new]
  resources :sessions, except: [:new, :destroy]
  resources :competitors, except: [:edit, :update]
  resources :matchups
  resources :matchup_types
  resources :bets, except: [:new]

  get "/signup", to: "users#new", as: :signup
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy"

  #Random matchup
  post "/random", to: "matchups#create_random_matchup"

  #Bets
  get "/placebet", to: "matchups#index"
  post "/placebet", to: "bets#new"

  #Admin capabilities
  get "/admin", to: "sessions#admin"
  post "/admin", to: "sessions#make_admin"
  post "/setwinner", to: "matchups#update"
  get "/leaderboards", to: "bets#show"
  post "/closeall", to: "matchups#close_all"




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetTr</title>
    <%= csrf_meta_tags %>

    <!-- BOOTSTRAP -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/master.css" media="screen" title="no title">
    <!-- END BOOTSTRAP -->

    <!-- FONT AWESOME -->
    <script src="https://use.fontawesome.com/d53c62c216.js"></script>
    <!-- END FONT AWESOME -->

    <!-- FONTS -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Oswald" />
    <!-- END FONTS -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <!-- NAVIGATION BAR -->

    <nav>

      <div class="logo">
        <a href="/">
          <h1>Bet.tr</h1>
          <h5>MAKE AMERICA BET.TR AGAIN</h5>
        </a>
      </div>

      <% if logged_in? %>
      <div class="nav_right">

        <div class="btn-group">
          <a class="btn btn-primary" href="/users/<%= current_user.id %>"><i style="color: white;" class="fa fa-user fa-fw"></i><%= current_user.username %></a>
          <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="fa fa-caret-down" title="Toggle dropdown menu"></span>
          </a>
          <ul class="dropdown-menu">
            <!-- <li><a href="#"><i class="fa fa-pencil fa-fw"></i> Edit</a></li>
            <li><a href="#"><i class="fa fa-trash-o fa-fw"></i> Delete</a></li> -->
            <!-- <li class="divider"></li> -->
            <% if session[:admin] == true %>
              <li><a href="/admin"><i class="fa fa-lock"></i> Admin</a></li>
            <% else %>
              <li><a href="/admin"><i class="fa fa-unlock"></i> Admin Login</a></li>
            <% end %>
            <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          </ul>
        </div>
          <h3><i class="fa fa-usd" aria-hidden="true"></i><%= current_user.balance %></h3>
          <% if session[:admin] == true %>
            <h3>ADMIN</h3>
          <% end %>

      </div>

        <% else %>

        <div class="nav_right">

          <div class="signin">
            <%= form_tag "/sessions" do %>
            <%= label_tag :username %>
            <%= text_field_tag :username %>
            <%= label_tag :password %>
            <%= password_field_tag :password %>
            <%= submit_tag "Sign in", :class => "sign_in_button" %>
            <% end %>
          </div>

          <div class="signup">
            <p><%= link_to "Not A Member? Sign Up", signup_path %></p>
          </div>

        </div>

      <% end %>

      <div class="links">
        <%= link_to "LEADERBOARDS", leaderboards_path %>
        <%= link_to "View All Matchups", matchups_path %>
        <%= link_to "View All Users", users_path %>
        <%= link_to "View All Competitors", competitors_path %>
      </div>

  </nav>

  <!-- END NAVIGATION BAR -->

    <div class="wrapper">
    <%= yield %>
    </div>
  </body>

  <!-- SCRIPTS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <!-- SCRIPTS -->

  <!-- JQUERY FOR PROFILE DROPDOWN -->
  <script>
  $(document).ready(function(){
    $(".dropdown-toggle").click(function(){
        $("div.btn-group").toggleClass("open");
        return false
    });
    $('html').click(function() {
            $('div.btn-group').removeClass('open');
        });
      });
  </script>
  <!-- END JQUERY -->

</html>